const host={name:"Pup",image:"assets/buddies/buddy-dog.webp"};
const restaurants=[
{id:"luna",emoji:"🌮",name:"Casa Luna",distance:"3.2 mi",price:"$$",style:"Modern Mexican",traits:["seafood","margaritas","light"],menu:{meal:["Fish tacos","Chicken enchiladas","Steak fajitas"],drink:["Lime margarita","Sweet tea","Sparkling water"],dessert:["Churros","Tres leches","No dessert"]}},
{id:"cactus",emoji:"🌵",name:"Cactus Cantina",distance:"1.8 mi",price:"$",style:"Fast & casual",traits:["cheap","quick","spicy"],menu:{meal:["Spicy chicken burrito","Carne asada tacos","Veggie bowl"],drink:["Horchata","Mexican Coke","Water"],dessert:["Cinnamon sopapillas","Flan","No dessert"]}},
{id:"azul",emoji:"🐟",name:"Azul Mar",distance:"7.4 mi",price:"$$$",style:"Coastal Mexican",traits:["seafood","upscale","novel"],menu:{meal:["Grilled mahi tacos","Shrimp enchiladas","Chicken mole"],drink:["Cucumber agua fresca","Paloma","Sparkling water"],dessert:["Coconut flan","Tres leches","No dessert"]}},
{id:"abuela",emoji:"🫔",name:"Abuela’s Table",distance:"5.1 mi",price:"$$",style:"Traditional family recipes",traits:["familiar","comfort","dessert"],menu:{meal:["Beef tamales","Cheese enchiladas","Chicken tortilla soup"],drink:["Sweet tea","Horchata","Water"],dessert:["Flan","Churros","No dessert"]}},
{id:"rojo",emoji:"🔥",name:"Rojo Taco Lab",distance:"6.6 mi",price:"$$",style:"Creative street tacos",traits:["novel","spicy","social"],menu:{meal:["Korean beef tacos","Hot honey chicken tacos","Avocado tostadas"],drink:["Mango agua fresca","Spicy margarita","Mexican Coke"],dessert:["Churro bites","Mexican chocolate cookie","No dessert"]}},
{id:"plaza",emoji:"🎉",name:"Plaza Fiesta",distance:"4.0 mi",price:"$$",style:"Lively neighborhood favorite",traits:["social","familiar","margaritas"],menu:{meal:["Steak fajitas","Combo enchiladas","Fish tacos"],drink:["House margarita","Sweet tea","Water"],dessert:["Fried ice cream","Sopapillas","No dessert"]}}
];
const diners=[
{id:"emma",name:"Emma",emoji:"👩🏽",intro:"Adventurous, loves fish and spicy food.",facts:["Orders seafood often","Usually stays within 10 miles","Dessert about half the time"],clues:{restaurant:"Emma ate fried catfish yesterday and wants something different tonight.",meal:"She still wants something light, but she is craving heat.",drink:"She is driving tonight.",dessert:"She skipped lunch, but says she does not want a heavy finish."},actual:{restaurant:"rojo",meal:"Hot honey chicken tacos",drink:"Mango agua fresca",dessert:"No dessert"},why:"Emma avoided another seafood meal, followed her adventurous streak to Rojo Taco Lab, chose a spicy lighter entrée, skipped alcohol because she was driving, and passed on dessert."},
{id:"marcus",name:"Marcus",emoji:"👨🏾",intro:"Predictable, budget-minded, and always hungry.",facts:["Favors familiar places","Usually orders beef","Almost always gets dessert"],clues:{restaurant:"Marcus paid for an expensive dinner last night.",meal:"He ran five miles this afternoon and wants the most filling option.",drink:"He has ordered Mexican Coke in three of his last four Mexican meals.",dessert:"His dessert streak is currently six dinners."},actual:{restaurant:"cactus",meal:"Carne asada tacos",drink:"Mexican Coke",dessert:"Cinnamon sopapillas"},why:"Marcus prioritized price and convenience, stayed with beef, continued his Mexican Coke habit, and protected his dessert streak."},
{id:"olivia",name:"Olivia",emoji:"👩🏻",intro:"Social planner who values atmosphere and group favorites.",facts:["Likes lively rooms","Often orders margaritas","Returns to trusted favorites"],clues:{restaurant:"Olivia is celebrating a promotion and invited two coworkers.",meal:"She wants something everyone at the table can share.",drink:"She is not driving and called this a celebration dinner.",dessert:"The group mentioned sharing one dessert for the table."},actual:{restaurant:"plaza",meal:"Steak fajitas",drink:"House margarita",dessert:"Fried ice cream"},why:"Olivia chose the liveliest familiar option, picked shareable fajitas, celebrated with the house margarita, and ordered the table-friendly fried ice cream."}
];
const stages=["restaurant","meal","drink","dessert"];
const points={restaurant:40,meal:30,drink:20,dessert:10};
const labels={restaurant:"Restaurant",meal:"Entrée",drink:"Drink",dessert:"Dessert"};
const app=document.querySelector("#app"),restartButton=document.querySelector("#restartButton");
let state={screen:"welcome",stageIndex:0,dinerIndex:0,picks:{},score:0};
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function hostCard(text){return `<div class="host-card"><img src="${host.image}" alt="Pup, Bite Buddy League host"><div><strong>${host.name}, League Host</strong><p>${text}</p></div></div>`}
function progress(){const done=state.stageIndex*diners.length+state.dinerIndex,total=stages.length*diners.length;return `<div class="progress-wrap"><div class="progress-meta"><span>${labels[stages[state.stageIndex]]} round</span><span>${done+1} of ${total}</span></div><div class="progress-track"><span style="width:${Math.round((done/total)*100)}%"></span></div></div>`}
function render(){restartButton.classList.toggle("hidden",state.screen==="welcome");if(state.screen==="welcome")return welcome();if(state.screen==="intro")return intro();if(state.screen==="play")return play();if(state.screen==="results")return results()}
function welcome(){app.innerHTML=`<div class="hero"><p class="eyebrow">Taco Tuesday Prediction Challenge</p><div class="hero-art">🌮🏆</div><h1>Know the person.<br>Predict the meal.</h1><p class="lead">Study three diners, use new clues as they are revealed, and predict their restaurant, entrée, drink, and dessert.</p><div class="mantra">People are the game. Food is the evidence.</div><button class="primary-button wide" id="start">Enter the Bite Buddy League</button></div>`;document.querySelector("#start").onclick=()=>{state.screen="intro";render()}}
function intro(){app.innerHTML=`<p class="eyebrow">Tonight’s Diners</p><h1 class="screen-title">Meet the people you’re predicting.</h1>${hostCard("Their final choices are already locked. I’ll reveal new information before every prediction.")}<div class="diner-grid">${diners.map(d=>`<article class="diner-card"><div class="diner-avatar">${d.emoji}</div><strong>${d.name}</strong><small>${d.intro}</small><div class="fact-list">${d.facts.map(f=>`<div class="fact">${f}</div>`).join("")}</div></article>`).join("")}</div><div class="actions"><button class="primary-button" id="begin">Begin Predictions</button></div>`;document.querySelector("#begin").onclick=()=>{state.screen="play";render()}}
function availableOptions(diner,stage){if(stage==="restaurant")return restaurants.map(r=>({value:r.id,title:r.name,subtitle:`${r.style} · ${r.distance} · ${r.price}`,emoji:r.emoji}));const restaurantId=state.picks[diner.id]?.restaurant;if(!restaurantId)return[];const r=restaurants.find(x=>x.id===restaurantId);return r.menu[stage].map(v=>({value:v,title:v,subtitle:r.name,emoji:stage==="meal"?"🍽️":stage==="drink"?"🥤":"🍰"}))}
function play(){const stage=stages[state.stageIndex],diner=diners[state.dinerIndex],selected=state.picks[diner.id]?.[stage];app.innerHTML=`${progress()}${hostCard(diner.clues[stage])}<div class="round-diner"><div class="diner-avatar">${diner.emoji}</div><div><h2>${diner.name}</h2><p>Predict the ${labels[stage].toLowerCase()}.</p></div></div><div class="${stage==="restaurant"?"restaurant-grid":"choice-grid"}">${availableOptions(diner,stage).map(o=>`<button class="option ${selected===o.value?"selected":""}" data-value="${o.value}"><span class="option-emoji">${o.emoji}</span><span><strong>${o.title}</strong><small>${o.subtitle}</small></span></button>`).join("")}</div><p class="lock-note">You may change this pick until you continue.</p><div class="actions"><button class="primary-button" id="continue" ${selected?"":"disabled"}>${state.dinerIndex===diners.length-1?`Finish ${labels[stage]} Round`:`Lock ${diner.name}`}</button></div>`;app.querySelectorAll(".option").forEach(btn=>btn.onclick=()=>{state.picks[diner.id]??={};state.picks[diner.id][stage]=btn.dataset.value;render()});const button=document.querySelector("#continue");if(button)button.onclick=()=>{if(!state.picks[diner.id]?.[stage])return;if(state.dinerIndex<diners.length-1)state.dinerIndex++;else if(state.stageIndex<stages.length-1){state.stageIndex++;state.dinerIndex=0}else{state.screen="results";calculateScore()}render()}}
function displayPick(stage,value){if(stage==="restaurant")return restaurants.find(r=>r.id===value)?.name||"—";return value||"—"}
function calculateScore(){state.score=0;diners.forEach(d=>stages.forEach(stage=>{const pick=state.picks[d.id]?.[stage];const actual=stage==="restaurant"?restaurants.find(r=>r.name===d.actual.restaurant)?.id:d.actual[stage];if(pick===actual)state.score+=points[stage]}))}
function getBoard(){try{return JSON.parse(localStorage.getItem("rmb-taco-board")||"[]")}catch{return[]}}
function saveScore(){const input=document.querySelector("#nickname"),name=(input.value||"Player").trim().slice(0,18)||"Player";const board=[...getBoard(),{name,score:state.score,date:new Date().toLocaleDateString("en-US")}].sort((a,b)=>b.score-a.score).slice(0,5);localStorage.setItem("rmb-taco-board",JSON.stringify(board));render()}
function results(){const board=getBoard();app.innerHTML=`<p class="eyebrow">Final Reveal</p><h1 class="screen-title">How well did you know them?</h1><div class="total-score"><strong>${state.score}</strong><span>out of 300 points</span></div>${diners.map(d=>{let dinerScore=0;const rows=stages.map(stage=>{const pick=state.picks[d.id]?.[stage],actualValue=stage==="restaurant"?restaurants.find(r=>r.name===d.actual.restaurant)?.id:d.actual[stage],correct=pick===actualValue;if(correct)dinerScore+=points[stage];return `<div class="answer-row ${correct?"correct":"wrong"}"><span>${labels[stage]}: ${displayPick(stage,pick)}</span><span>${correct?`✓ +${points[stage]}`:`✕ ${d.actual[stage]}`}</span></div>`}).join("");return `<article class="reveal-card"><div class="reveal-head"><strong>${d.emoji} ${d.name}</strong><span class="score-pill">${dinerScore}/100</span></div>${rows}<p class="explanation">${d.why}</p></article>`}).join("")}<h2>Local Leaderboard</h2><div class="name-entry"><input id="nickname" maxlength="18" placeholder="Your nickname" aria-label="Your nickname"><button class="secondary-button" id="save">Save Score</button></div>${board.length?`<table class="leaderboard"><thead><tr><th>Player</th><th>Date</th><th>Score</th></tr></thead><tbody>${board.map((r,i)=>`<tr><td>${i+1}. ${escapeHtml(r.name)}</td><td>${escapeHtml(r.date)}</td><td>${r.score}</td></tr>`).join("")}</tbody></table>`:`<p class="lead">No saved scores yet. Be the first league leader.</p>`}<div class="actions"><button class="primary-button" id="again">Play Again</button></div><p class="feedback-prompt">After playing, ask yourself: Did a clue make you change your mind? Did each final choice feel believable?</p>`;document.querySelector("#save").onclick=saveScore;document.querySelector("#again").onclick=reset}
function reset(){state={screen:"welcome",stageIndex:0,dinerIndex:0,picks:{},score:0};render()}
restartButton.onclick=reset;render();